# Generated by Django 3.2.4 on 2021-06-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('save_code', models.TextField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, verbose_name='Başlık')),
                ('explonation', models.TextField(max_length=1000, verbose_name='Açıklama')),
                ('link', models.TextField(max_length=100, verbose_name='Link')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('photo', models.ImageField(default='Ek dosya', null=True, upload_to='uploads/', verbose_name='Resim')),
            ],
        ),
    ]
