# Generated by Django 3.2.4 on 2021-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210618_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
