# Generated by Django 3.2.4 on 2021-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_form_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='link',
            field=models.TextField(max_length=1000, null=True, verbose_name='Link'),
        ),
    ]
