# Generated by Django 3.2.4 on 2021-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='form',
            name='explonation',
            field=models.TextField(max_length=1000, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='form',
            name='link',
            field=models.TextField(max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.TextField(max_length=100, null=True, verbose_name='Başlık'),
        ),
    ]
